name: egc_website
description: University administration system.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.0.0
  shelf_cors_headers: ^0.1.0
  firebase_dart: ^1.1.4
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  mime: ^1.0.6

  



dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
